---
- Nobody knows for certain.
- Unknown.
- Unknowable.
- Because.
- Why not?
- The alignment of the planets caused that.
- Quantum entanglement.
- "Because #{deity} wills it"
- Have you tried staring really, really hard at it?
- Have you tried deleting it all and starting again?
- Code has gained sentience.
- Ambient temperature not at recommended levels.
- Sun at incorrect angle.
- Moon at incorrect angle.
- Computer too far to the left.
- Computer too far to the right.
- Computer too high.
- Computer too low.
- Computer in unknown n-dimensional space.
